config_mouse.sh
config_display.sh
config_wallpapers.sh

pkill ssh-agent
eval "$(ssh-agent)"

killall slstatus
slstatus &

#killall xcompmgr
#xcompmgr &

killall unclutter
unclutter -root -idle 2 -jitter 5 &

killall sxhkd
sxhkd &

killall dunst
dunst &

pkill syncthing
syncthing --no-browser &

#xset -dpms
#xset s off

pkill anki
#anki --syncserver &

# Run dynamic windows manager
# killall dwm
# exec dwm >/dev/null 2>&1
#
# while true; do
    # Log stderror to a file
dwm
    # No error logging
    #dwm >/dev/null 2>&1
# done

